# netlify.toml

[build]
  publish = "/dist/apps/ng-demos"
  command = "nx run ng-demos:build"


[[redirects]]
  from = "/about"
  to = "/presenty-landing-site/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/ng-demos/index.html"
  status = 200
