# netlify.toml

# Configuration for ng-demos and presenty-landing-site
[context.main]
  publish = "/dist/apps/ng-demos"
  command = "bash ./build.sh"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF . ../apps/ng-demos/ ../apps/presenty-landing-site/"

# Configuration for evonix-site
[context.evonix]
  publish = "/dist/apps/evonix-site"
  command = "nx run evonix-site:build"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF . ../apps/evonix-site/"