export const GPTPrivacyPolicy = `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Presenty API privacy policy for Presenty GPT</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 20px; }
        h2 { color: #333; }
        p { color: #666; }
    </style>
</head>
<body>
    <h2>Presenty API privacy policy for Presenty GPT</h2>

    <h3>Introduction</h3>
    <p>This Privacy Policy outlines how we collect, use, store, and protect the personal information provided to us through the Presenty GPT Service API, specifically relating to the <code>save</code> endpoint.</p>

    <h3>Information Collection</h3>
    <p>When you use our GPT Service API's <code>save</code> endpoint, we collect the following information:</p>
    <ul>
        <li><strong>Markdown Content</strong>: This is the GPT-generated markdown content that you provide.</li>
        <li><strong>Presentation Name</strong>: The name of the presentation associated with the markdown content.</li>
        <li><strong>Presentation ID</strong> (optional): An identifier for when updating existing content.</li>
        <li><strong>Dall.E Images</strong> (optional): Images generated by Dall.E, including their base64 encoded chunks and filenames.</li>
    </ul>

    <h3>Use of Information</h3>
    <p>The information collected is used for the following purposes:</p>
    <ul>
        <li>To store and manage the markdown content and associated presentation details.</li>
        <li>To process and handle Dall.E generated images for integration with markdown content.</li>
        <li>To enhance and improve our API services.</li>
    </ul>

    <h3>Data Storage and Security</h3>
    <p>We are committed to ensuring the security of your data. We store your information on secure servers and take appropriate measures to protect it from unauthorized access, disclosure, alteration, or destruction.</p>

    <h3>Data Sharing and Disclosure</h3>
    <p>We do not sell, trade, or rent your personal identification information to others. We may share generic aggregated demographic information not linked to any personal identification information regarding visitors and users with our business partners, trusted affiliates, and advertisers for the purposes outlined above.</p>

    <h3>Your Rights</h3>
    <p>You have the right to access, correct, or delete your personal information that we hold. You can request this by contacting us using the details provided below.</p>

    <h3>Changes to This Privacy Policy</h3>
    <p>We reserve the right to update or change our Privacy Policy at any time. We will notify you of any changes by posting the new Privacy Policy on this page. You are advised to review this Privacy Policy periodically for any changes.</p>

    <h3>Contacting Us</h3>
    <p>If you have any questions about this Privacy Policy or the practices of this site, please contact us at: <a href="mailto:salmanaziz497@gmail.com">salmanaziz497@gmail.com</a></p>

</body>
</html>
`;