name: Deploy Backend

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get last commit message
      id: get_commit_message
      run: echo "LAST_COMMIT_MESSAGE=$(git log -1 --pretty=%B)" >> $GITHUB_ENV

    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies.
      run: npm ci

    - name: Build Nx Web app
      run: npx nx run backend:build:production

    - name: Install dependencies.
      run: npm ci
      working-directory: dist/apps/backend

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.PRESENTATION_AZURE_SECRET }}

    - name: Deploy Backend ARM Template
      if: contains(env.LAST_COMMIT_MESSAGE, 'api')
      uses: azure/arm-deploy@v1
      with:
        resourceGroupName: presentation-resources
        template: infra/backend.azure-template.json
        parameters: infra/backend.azure-parameters.json
        additionalArguments: '--parameters someSecretValue="${{ secrets.SOME_SECRET_VALUE }}"'

    - name: Deploy NestJS to App Service
      if: contains(env.LAST_COMMIT_MESSAGE, 'api')
      uses: azure/webapps-deploy@v2
      with:
        app-name: presentation
        package: dist/apps/backend 

    - name: Logout of Azure
      run: az logout

